### ISSUE TITLE
Spam Capture Fails on LiteralField

### ISSUE THREAD

**Issue by phptek** [vulcandigital/silverstripe-pagefeedback#12]
Due to the way the form is scaffolded in `PageFeedbackThumbsForm::__construct()` any spam capture fetaure that tries to call a field's `actionName()` will fail. They are expecting instances of `FormAction` AFAICT.

Using the folloiwng config, with the module as-is, you'll get errors as soon as you select one of the "+1" / "-1" buttons:

```yml
---
Name: 'mysite-spam'
After:
  - 'requestprocessors'
  - 'akismet'
---

SilverStripe\SpamProtection\Extension\FormSpamProtectionExtension:
  default_spam_protector: UndefinedOffset\NoCaptcha\Forms\NocaptchaProtector
```
